services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: medical_rag_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./datasets:/app/datasets
    restart: always

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: medical_rag_frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: always
